### ISSUE TITLE
Duplicate column names in generated table types

### ISSUE THREAD

**Issue by kkorenius** [jawj/zapatos#93]
Thank you for providing us with this great library.

Zapatos version 4.0.2 onwards seems to suffer from duplicate column names in generated types. This happens when a same table exists in multiple schemas.

I believe the culprit is the query in <https://github.com/jawj/zapatos/blob/master/src/generate/tables.ts#L50>. The query does a left join to table pg_class, without limiting the namespace/schema.

It should be also noted that the preceding query for indexes (<https://github.com/jawj/zapatos/blob/master/src/generate/tables.ts#L156>) seems also to lack the schema restriction, thus pulling indexes from other schemas as well.

**Comment by jawj** [comment]
Yikes, that's very possible — I just changed that from a nested subquery to a left join to work around a problem with CockroachDB, so maybe I screwed up.

I'll try to look at this later today.

**Comment by jawj** [comment]
OK, I think I've fixed both those queries with the latest commit. 

I haven't had much time for testing it (but so far it doesn't seem to break anything when using a single schema). 

If you were able to test it by checking out `master` and using `npm link`, it would be much appreciated.

**Comment by kkorenius** [comment]
That was quick :) I took this update for a spin. Some comments: 

- The duplicate columns are gone. Excellent!

- For the indexes we still get some duplicates but fewer than before (I think we got some even before version 4.0.2). This does not affect compilation as index names are used in a union type. Probably the query for indexes should link to pg_namespace or something like that.

- I also noticed that formerly we got column definitions for views (non-materialized) as well. The table query in <https://github.com/jawj/zapatos/blob/master/src/generate/tables.ts#L22> returns these and types them as a 'table'. Now these table definitions are still generated but now without any columns. Personally, I would find these view types useful, we do use them. They should not be updatable though.

**Comment by jawj** [comment]
>     * The duplicate columns are gone. Excellent!

Great.

>     * For the indexes we still get some duplicates but fewer than before (I think we got some even before version 4.0.2). This does not affect compilation as index names are used in a union type. Probably the query for indexes should link to pg_namespace or something like that.

That's odd. The relevant query does now limit by `tablename` and `schemaname`. Anyway, for now I've decided to cheat and use `SELECT DISTINCT`. :)

>     * I also noticed that formerly we got column definitions for views (non-materialized) as well. The table query in https://github.com/jawj/zapatos/blob/master/src/generate/tables.ts#L22 returns these and types them as a 'table'. Now these table definitions are still generated but now without any columns. Personally, I would find these view types useful, we do use them. They should not be updatable though.

Oh, I'm surprised that this changed But anyway, I took the opportunity to simplify the query in  `relationsForSchema` and to deal more explicitly with views and foreign tables. 

You should now find that views (and foreign tables) have `Insertable` and `Updatable` interfaces defined as usual if they're reported as insertable in `information_schema.tables`, and as `{ [key: string]: never }` if they're reported as not being insertable.

If you wouldn't mind testing `master` again, could you let me know if that all works for you?

I've also split out the `AllTables` type into various others (`AllBaseTables`, `AllStandardViews`, etc.), so all in all this will be a potentially-breaking change that would need to be released as 5.0.

**Comment by kkorenius** [comment]
I cloned again the master branch and tested our app with it. Everything seems to work.

Duplicate indexes are gone now. Also, the views gets column definitions for selectables and whereables, and like you said, the Updatables and Insertables are typed as `{ [key: string]: never }` now. Magic.

Thank you!

**Comment by jawj** [comment]
Great. This is now released as 5.0.
